app/home/forms.py
# coding:utf8
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField, StringField, PasswordField, FileField, TextAreaField
from wtforms.validators import DataRequired, EqualTo, Email, Regexp, ValidationError
from app.models import User


class RegistForm(FlaskForm):
    name = StringField(
        label="昵称",
        validators=[
            DataRequired("请输入昵称！")
        ],
        description="昵称",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入昵称！",
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱！"),
            Email("邮箱格式不正确！")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入邮箱！",
        }
    )
    phone = StringField(
        label="手机",
        validators=[
            DataRequired("请输入手机！"),
            Regexp("1[3458]\\d{9}", message="手机格式不正确！")
        ],
        description="手机",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入手机！",
        }
    )
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码！",
        }
    )
    repwd = PasswordField(
        label="确认密码",
        validators=[
            DataRequired("请输入确认密码！"),
            EqualTo('pwd', message="两次密码不一致！")
        ],
        description="确认密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入确认密码！",
        }
    )
    submit = SubmitField(
        '注册',
        render_kw={
            "class": "btn btn-lg btn-success btn-block",
        }
    )

    def validate_name(self, field):
        name = field.data
        user_count = User.query.filter_by(name=name).count()
        if user_count == 1:
            raise ValidationError("昵称已经存在！")

    def validate_email(self, field):
        email = field.data
        user_count = User.query.filter_by(email=email).count()
        if user_count == 1:
            raise ValidationError("邮箱已经存在！")

    def validate_phone(self, field):
        phone = field.data
        user_count = User.query.filter_by(phone=phone).count()
        if user_count == 1:
            raise ValidationError("手机号码已经存在！")


class LoginForm(FlaskForm):
    name = StringField(
        label="账号",
        validators=[
            DataRequired("请输入账号！")
        ],
        description="账号",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入账号！",
        }
    )
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码！",
        }
    )
    submit = SubmitField(
        '登录',
        render_kw={
            "class": "btn btn-lg btn-primary btn-block",
        }
    )

    def validate_name(self, field):
        name = field.data
        user = User.query.filter_by(name=name).count()
        if user == 0:
            raise ValidationError("账号不存在！")



class UserdetailForm(FlaskForm):
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱！"),
            Email("邮箱格式不正确！")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入邮箱！",
        }
    )
    phone = StringField(
        label="手机",
        validators=[
            DataRequired("请输入手机！"),
            Regexp("1[3458]\\d{9}", message="手机格式不正确！")
        ],
        description="手机",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入手机！",
        }
    )
    face = FileField(
        label="头像",
        validators=[
            DataRequired("请上传头像！")
        ],
        description="头像",
    )
    info = TextAreaField(
        label="简介",
        validators=[
            DataRequired("请输入简介！")
        ],
        description="简介",
        render_kw={
            "class": "form-control",
            "rows": 10
        }
    )
    submit = SubmitField(
        '保存修改',
        render_kw={
            "class": "btn btn-success",
        }
    )


class PwdForm(FlaskForm):
    old_pwd = PasswordField(
        label="旧密码",
        validators=[
            DataRequired("请输入旧密码！")
        ],
        description="旧密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入旧密码！",
        }
    )
    new_pwd = PasswordField(
        label="新密码",
        validators=[
            DataRequired("请输入新密码！"),
        ],
        description="新密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入新密码！",
        }
    )
    submit = SubmitField(
        '修改密码',
        render_kw={
            "class": "btn btn-success",
        }
    )

    def validate_old_pwd(self, field):
        from flask import session
        old_pwd = field.data
        name = session.get('user_name')
        user = User.query.filter_by(name=name).first()

        if not user.check_pwd(old_pwd):
            raise ValidationError("旧密码错误！")


class CommentForm(FlaskForm):
    content = TextAreaField(
        label="内容",
        validators=[
            DataRequired("请输入内容！"),
        ],
        description="内容",
        render_kw={
            "id": "input_content",

        }
    )
    submit = SubmitField(
        '提交评论',
        render_kw={
            "class": "btn btn-success",
            "id": "btn-sub"
        }
    )

app/home/__init__.py
# encoding: utf8

from flask import Blueprint
home = Blueprint("home", __name__)
import app.home.views

app/home/views.py
# encoding: utf8

from . import home
from flask import render_template, redirect, url_for, flash, session, request, Response
from app.home.forms import RegistForm, LoginForm, UserdetailForm, PwdForm, CommentForm
from app.models import User, Userlog, Preview, Tag, Movie, Comment, Moviecol
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
from app.exts import db
import uuid
from functools import wraps
import os
from app.config import FACE_DIR
import datetime
from app import rd


# 登录装饰器
def user_login_required(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if 'user_logged_in' in session:
            return func(*args, **kwargs)
        return redirect(url_for('home.login', next=request.url))

    return wrapper


# 功能函数：修改文件名
def change_filename(filename):
    file_extention = (os.path.splitext(filename))[1]  # 分离文件的路径，获取文件扩展名
    filename = datetime.datetime.now().strftime("%Y%m%d%H%M%S") + \
               str(uuid.uuid4().hex) + file_extention
    return filename


# 首页
@home.route("/", methods=["GET"])
@home.route("/<int:page>/", methods=["GET"])
def index(page=None):
    if page == None:
        page = 1

    tags = Tag.query.all()

    #分页
    page_data = Movie.query

    tid = request.args.get("tid", 0)  # 标签(注：如果tid为空，则给它赋值0，后面以此类推）
    if int(tid) != 0:
        page_data = page_data.filter_by(tag_id=int(tid))

    star = request.args.get("star", 0)  # 星级
    if int(star) != 0:
        page_data = page_data.filter_by(star=int(star))

    time = request.args.get("time", 0)  # 时间(1表示"最近"，2表示"更早")
    if int(time) == 1:
        page_data = page_data.order_by(Movie.addtime.desc())
    elif int(time) == 2:
        page_data = page_data.order_by(Movie.addtime.asc())

    pm = request.args.get("pm", 0)  # 播放数量（1表示 从高到底，2表示 从低到高）
    if int(pm) == 1:
        page_data = page_data.order_by(Movie.playnum.desc())
    elif int(pm) == 2:
        page_data = page_data.order_by(Movie.playnum.asc())

    cm = request.args.get("cm", 0)  # 评论数量（1表示 从高到底，2表示 从低到高）
    if int(cm) == 1:
        page_data = page_data.order_by(Movie.commentnum.desc())
    elif int(cm) == 2:
        page_data = page_data.order_by(Movie.commentnum.asc())

    page_data = page_data.paginate(page=page, per_page=10)

    p = dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm
    )

    return render_template("home/index.html", tags=tags, p=p, page_data=page_data)


# 登录
@home.route("/login/", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=data.get('name')).first()
        if not user.check_pwd(data.get('pwd')):
            flash('身份验证失败！', 'err')
            return redirect(url_for('home.login'))
        session['user_logged_in'] = True
        session['user_name'] = user.name
        session['user_id'] = user.id

        userlog = Userlog(
            user_id=user.id,
            ip=request.remote_addr,
        )
        db.session.add(userlog)
        db.session.commit()
        return redirect(request.args.get("next") or url_for('home.index', page=1))
    return render_template("home/login.html", form=form)


# 退出
@home.route("/logout/")
@user_login_required
def logout():
    # session.clear()   #这种方法太粗暴，某些情况下会影响flash的消息闪现，不推荐使用
    session.pop('user_logged_in', None)
    session.pop('user_name', None)
    session.pop('user_id', None)
    return redirect(url_for('home.login'))


# 会员注册
@home.route("/register/", methods=["GET", "POST"])
def register():
    form = RegistForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            name=data.get('name'),
            pwd=generate_password_hash(data.get('repwd')),
            email=data.get('email'),
            phone=data.get('phone'),
            uuid=uuid.uuid4().hex
        )
        db.session.add(user)
        db.session.commit()
        flash('注册成功，请登录!', 'ok')
        return redirect(url_for('home.login'))
    return render_template("home/register.html", form=form)


# 会员资料
@home.route("/user/", methods=["GET", "POST"])
@user_login_required
def user():
    form = UserdetailForm()
    # 查询并显示用户原有信息
    # user = User.query.get(int(session['user_id']))
    user = User.query.filter_by(name=session.get('user_name')).first()
    if request.method == "GET":
        form.email.data = user.email
        form.phone.data = user.phone
        form.info.data = user.info
    # 进入会员资料修改页面时，头像可以不修改
    form.face.validators = []

    if form.validate_on_submit():
        data = form.data
        # 处理不允许重复的值
        email_count = User.query.filter_by(email=data.get('email')).count()
        if email_count == 1 and user.email != data.get('email'):
            flash('该邮箱已存在!', 'err')
            return redirect(url_for('home.user'))
        phone_count = User.query.filter_by(phone=data.get('phone')).count()
        if phone_count == 1 and user.phone != data.get('phone'):
            flash('该手机号码已存在!', 'err')
            return redirect(url_for('home.user'))
        # file_face 不为空，说明用户上传了新头像， 获取并保存新头像
        file_face = secure_filename(form.face.data.filename)
        if file_face != "":
            if not os.path.exists(FACE_DIR):
                os.makedirs(FACE_DIR)
                os.chmod(FACE_DIR, "rw")
            user.face = change_filename(file_face)
            form.face.data.save(FACE_DIR + user.face)
        # 获取其他项
        user.email = data.get('email')
        user.phone = data.get('phone')
        user.info = data.get('info')
        # 更新数据库
        db.session.add(user)
        db.session.commit()
        flash('会员资料修改成功!', 'ok')
        return redirect(url_for('home.user'))
    return render_template("home/user.html", form=form, user=user)


# 修改密码
@home.route("/pwd/", methods=["GET", "POST"])
@user_login_required
def pwd():
    form = PwdForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=session.get('user_name')).first()
        user.pwd = generate_password_hash(data.get('new_pwd'))
        db.session.add(user)
        db.session.commit()
        flash('密码修改成功，请重新登录!', 'ok')
        return redirect(url_for('home.logout'))
    return render_template("home/pwd.html", form=form)


# 会员评论
@home.route("/comments/<int:page>/")
@user_login_required
def comments(page=None):
    if page == None:
        page = 1
    page_data = Comment.query.join(Movie).join(User).filter(
        Movie.id == Comment.movie_id, User.id == session.get('user_id')).order_by(
        Comment.addtime.desc()).paginate(page=page, per_page=3)
    return render_template("home/comments.html", page_data=page_data)


# 会员登录日志
@home.route("/loginlog/<int:page>/", methods=["GET"])
@user_login_required
def loginlog(page=None):
    if page is None:
        page = 1
    page_data = Userlog.query.join(User).filter(
        User.id == Userlog.user_id).order_by(
        Userlog.addtime.desc()).paginate(page=page, per_page=10)
    return render_template("home/loginlog.html", page_data=page_data)


# 添加电影收藏
@home.route("/moviecol/add/", methods=["GET"])
@user_login_required
def moviecol_add():
    uid = request.args.get("uid", "")
    mid = request.args.get("mid", "")
    moviecol_count = Moviecol.query.filter_by(
        user_id=int(uid),
        movie_id=int(mid)
    ).count()
    if moviecol_count == 1:   #电影已收藏
        data = dict(ok=0)

    if moviecol_count == 0:   #电影未收藏，执行收藏（存入数据库）
        moviecol = Moviecol(
            user_id=int(uid),
            movie_id=int(mid)
        )
        db.session.add(moviecol)
        db.session.commit()
        data = dict(ok=1)
    import json
    return json.dumps(data)



# 电影收藏
@home.route("/moviecol/<int:page>/")
@user_login_required
def moviecol(page=None):
    if page == None:
        page = 1
    page_data = Moviecol.query.join(Movie).join(User).filter(
        User.id == session.get('user_id'),
        Movie.id == Moviecol.movie_id,
    ).order_by(
        Moviecol.addtime.desc()).paginate(page=page, per_page=3)
    return render_template("home/moviecol.html", page_data=page_data)



# 取消电影收藏，并确保取消收藏后留在当前分页（而不是每次删除后自动跳转回第一页）
@home.route("/moviecol/del/<int:id>/<int:page>/", methods=['GET'])
@user_login_required
def moviecol_del(id=None, page=None):
    moviecol = Moviecol.query.filter_by(movie_id=id).first_or_404()
    db.session.delete(moviecol)
    db.session.commit()
    flash('取消收藏成功!', 'ok')
    return redirect(url_for('home.moviecol', page=page))



# 上映预告，封面轮播效果
@home.route("/animation/")
def animation():
    data = Preview.query.all()
    return render_template("home/animation.html", data=data)


# 搜索
@home.route("/search/<int:page>/")
def search(page=None):
    if page == None:
        page = 1
    key = request.args.get("key", "")  # 获取搜索关键字，默认为空
    page_data = Movie.query.filter(
        Movie.title.ilike('%' + key + '%')).order_by(  # 模糊匹配
        Movie.addtime.desc()).paginate(page=page, per_page=2)
    page_data.key = key
    #获取搜索结果数量
    movie_count = Movie.query.filter(Movie.title.ilike('%' + key + '%')).count()
    return render_template("home/search.html", key=key, page_data=page_data, movie_count=movie_count)


# dplayer播放页面
@home.route("/video/<int:id>/<int:page>/", methods=["GET", "POST"])
def video(id=None, page=None):
    movie = Movie.query.join(Tag).filter(
        Tag.id == Movie.tag_id,
        Movie.id == int(id),
    ).first_or_404()

    #分页
    if page == None:
        page = 1
    page_data = Comment.query.join(Movie).join(User).filter(
        Movie.id == movie.id, User.id == Comment.user_id).order_by(
        Comment.addtime.desc()).paginate(page=page, per_page=3)

    #获取评论相关信息并存入数据库
    form = CommentForm()
    if form.validate_on_submit():
        data = form.data
        comment = Comment(
            content = data.get('content'),
            movie_id = movie.id,
            user_id = session.get('user_id')
        )

app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static',filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/animate.css') }}">
    <style>
        .navbar-brand>img {
            display: inline;
        }
        .media{
            padding:3px;
            border:1px solid #ccc
        }
    </style>
    {% block css %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index',page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static',filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="key_movie">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="do_search"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index', page=1) }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                {% if session.user_logged_in %}
                    <li>
                        <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;{{ session.user_name }}</a>
                    </li>
                    <li>
                        <a class="curlink" href="{{ url_for('home.logout') }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                    </li>
                {% else %}
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register') }}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}{% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;Jiaxuan 2017&nbsp;
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static',filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static',filename='lazyload/jquery.lazyload.min.js') }}"></script>
<!--<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>-->
<script src="{{ url_for('static', filename='js/holder.min.js') }}"></script>
<script>
    $(function() {
        new WOW().init();
    })
</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        $("#do_search").click(function(){
            var key = $("#key_movie").val();
            location.href = "{{ url_for('home.search',page=1) }}?key=" + key;
        });
    });
</script>
{% block js %}{% endblock %}
</body>
</html>

app/templates/home/index.html
{% extends "home/layout.html" %}

{% import "ui/home_page.html" as pg %}

{% block content %}
<!--热门电影-->
<section id="hotmovie" style="margin-top:76px">
    <div class="container">
        <div class="row wow fadeInRight" data-wow-delay="0.6s">
            <div class="row">
                <iframe class="wow fadeIn" width="100%" height="375px" frameborder=0 scrolling=no src="{{ url_for('home.animation') }}"></iframe>
            </div>
        </div>
    </div>
</section>
<!--热门电影-->
<!--电影列表-->
<section id="movielist">
    <div class="container">
        <div class="row wow fadeIn" data-wow-delay="0.6s">
            <div class="col-md-12 table-responsive">
                <table class="table text-left table-bordered" id="movietags">
                    <tr>
                        <td style="width:10%;">电影标签</td>
                        <td style="width:90%;">
                            {% for tag in tags %}
                            <a href="{{ url_for('home.index',page=1) }}?tid={{ tag.id }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm={{ p['cm'] }}"
                               class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;{{ tag.name }}</a>
                            &nbsp;
                            {% endfor %}
                    </tr>
                    <tr>
                        <td>电影星级</td>
                        <td>
                            {% for v in range(1,6) %}
                            <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ v }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm={{ p['cm'] }}"
                               class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;{{ v }}星</a>
                            &nbsp;
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td>上映时间</td>
                        <td>
                            <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time=1&pm={{ p['pm'] }}&cm={{ p['cm'] }}" class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;最近</span></a>
                            &nbsp;
                            <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time=2&pm={{ p['pm'] }}&cm={{ p['cm'] }}" class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;更早</span></a>
                        </td>
                    </tr>
                    <tr>
                        <td>播放数量</td>
                        <td>
                            <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm=1&cm={{ p['cm'] }}" class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span></a>
                            &nbsp;
                            <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm=2&cm={{ p['cm'] }}" class="label label-danger"><span class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                    <tr>
                        <td>评论数量</td>
                        <td>
                            <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm=1" class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span></a>
                            &nbsp;
                            <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm=2" class="label label-danger"><span class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                </table>
            </div>
            {% for item in page_data.items %}
            <div class="col-md-3">
                <div class="movielist text-center">
                    <!--<img data-original="holder.js/262x166"
                             class="img-responsive lazy center-block" alt="">-->
                    <img src="{{ url_for('static',filename='uploads/' + item.logo) }}" class="img-responsive center-block" alt="">
                    <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                        <span style="color:#999;font-style: italic;">{{ item.title }}</span><br>
                        <div>
                            <!--显示数量为 item.star 的实心星星图标-->
                            {% for val in range(1,item.star+1) %}
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            {% endfor %}
                            <!--显示数量为 5-item.star 的空心星星图标-->
                            {% for val in range(1,5-item.star+1) %}
                            <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                            {% endfor %}
                        </div>
                    </div>
                    <a href="{{ url_for('home.video',id=item.id,page=1) }}" class="btn btn-primary" target="_blank" role="button"><span class="glyphicon glyphicon-play"></span>&nbsp;播放</a>
                </div>
            </div>
            {% endfor %}

            <div class="col-md-12">
                {{ pg.page(page_data,'home.index') }}
            </div>
        </div>
    </div>
</section>
<!--电影列表-->
{% endblock %}

app/templates/home/search.html
{% extends "home/home.html" %}

{% import "ui/search_page.html" as pg %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb" style="margin-top:6px;">
                <li>与"{{ key }}"有关的电影，共{{ movie_count }}部</li>
            </ol>
        </div>
        <div class="col-md-12">
            {% for item in page_data.items %}
                <div class="media">
                    <div class="media-left">
                        <a href="{{ url_for('home.video', id=item.id, page=1) }}">
                            <img class="media-object" style="width:131px;height:83px;" src="{{ url_for('static', filename='uploads/' + item.logo ) }}" alt="{{ item.title }}">
                            <!--<img class="media-object" src="holder.js/131x83" alt="{{ item.title }}">-->
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">{{ item.title }}<a href="{{ url_for('home.video', id=item.id, page=1) }}" class="label label-primary pull-right"><span class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                        {{ item.info }}
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-md-12 text-center">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {{ pg.page(page_data,'home.search') }}
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}

app/templates/home/sidebar.html
<div class="col-md-3">
    <div class="list-group">
        <a id="item-1" href="{{ url_for('home.user') }}" class="list-group-item">
            <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
        </a>
        <a id="item-2" href="{{ url_for('home.pwd') }}" class="list-group-item">
            <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
        </a>
        <a id="item-3" href="{{ url_for('home.comments', page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
        </a>
        <a id="item-4" href="{{ url_for('home.loginlog', page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
        </a>
        <a id="item-5" href="{{ url_for('home.moviecol', page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
        </a>
    </div>
</div>